Code/Brandon/Django/labs/labs/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('contacts/', include('Contacts.urls')),
    path('admin/', admin.site.urls),
    path('shorts/', include('shorts.urls')),
    path('library/', include('library.urls'))
]

Code/Brandon/Django/labs/shorts/urls.py
from django.urls import path

from . import views

app_name = 'shorts'

urlpatterns = [
    # index view
    path('', views.index, name='index'),
    # create view that redirects to index page after saving
    path('create/', views.create, name='create'),
    # passes the short url to the visit page that will pull the site byusing the short url then render the page to the full url
    path('<str:short_url>/', views.visit, name='visit'),
    # Sends to the delete view that will redirect to the index page updated
    path('delete/<int:url_id>/', views.delete, name='delete'),
]

Code/Brandon/Django/labs/shorts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
import random
import string
from .models import Shorten

# Main index view page
def index(request):
    urls = Shorten.objects.order_by('site_name')
    context = {'urls': urls}
    return render(request,'shorts/index.html',context)

# Creates a new short url but taking the data from th e form on the index page and storing it in the models.
def create(request):
    site_name = request.POST['name']
    site_url = request.POST['url']
    # below will createe the 5 digit/alpha  to bel placed in the url
    lettersAndDigits = string.ascii_letters + string.digits
    short_url = ''.join(random.choice(lettersAndDigits) for i in range(5))

    urls = Shorten(site_name=site_name,site_url=site_url,short_url=short_url, clicks=0)
    urls.save()

    return redirect('shorts:index')

# This takes the data from the model (site url etc) using the short url and redirects to the full site url
def visit(request, short_url):
    urls = Shorten.objects.get(short_url=short_url)
    urls.clicks += 1 
    urls.save()

    return redirect(urls.site_url)

# following function is for removing a url from the database
def delete(request, url_id):
    urls = Shorten.objects.get(id=url_id)
    urls.delete()
    return redirect('shorts:index')

Code/Brandon/Django/labs/shorts/templates/shorts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Pure CSS CDN --- -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% load static%}
    <link rel="stylesheet" type="text/css" href="{% static 'shorts/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">URL Shortener</span>
    </nav>
    <div class="main-bod">
        <div class="card submit-card">
            <div class="card-header">
              Shorten Your really long URL
            </div>
            <div class="card-body">
                <form action="{% url 'shorts:create' %}" method="POST" class="pure-form">
                    {% csrf_token %}
                    <input type="text" class="form-control" placeholder="Website Name" name="name">
                    <input type="text" class="form-control" placeholder="Website URL" name = "url">
                    <button type="submit" class="pure-button">Shorten</button>
                </form>
            </div>
          </div>
<!-- This is the div for the display/'' -->
    <div class="main-cards">
    {% for url in urls %}
    <div class="card card-bod" style="width: 18rem;">
        <div class="card-header">
          Site Name: {{url.site_name}}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Site URL: {{url.site_url}}</li>
          <li class="list-group-item">Short Key: <a href="{% url 'shorts:visit' url.short_url %}">{{url.short_url}}</a></li>
          <li class="list-group-item">Times visited: {{url.clicks}} </li>
          <li class="list-group-item"><a href="{% url 'shorts:delete' url.id %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Delete</a></li>
        </ul>
        
      </div>

    {% endfor %}
    </div>
    </div>
</body>
</html>