Code/Teddy/Django/todoproj/todoapp/urls.py
from django.urls import path
from . import views

app_name = 'todoapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('savetodo/', views.savetodo, name='savetodo'),
    path('completetodo/', views.completetodo, name='completetodo'),
    path('deletetodo/<todo_item_id>/', views.deletetodo, name='deletetodo'),
]

Code/Teddy/Django/todoproj/todoproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

Code/Teddy/Django/todoproj/todoapp/models.py
from django.db import models

class TodoItemPriority(models.Model):
    name = models.CharField(max_length=50)
    order = models.IntegerField()

    def __str__(self):
        return str(self.order) + ') ' + self.name

    def get_class_name(self):
        return self.name.lower().replace(' ', '_')


class TodoItem(models.Model):
    text = models.CharField(max_length=500)
    priority = models.ForeignKey(TodoItemPriority, on_delete=models.PROTECT, related_name='todo_items')
    created_date = models.DateTimeField(auto_now_add=True)
    completed_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.text + ' (' + self.priority.name + ')'

    def is_completed(self):
        return self.completed_date is not None

Code/Teddy/Django/todoproj/todoapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import TodoItem, TodoItemPriority
from django.utils import timezone
import random

def index(request):
    emoji = random.choice(['😀', '😁', '😴'])
    todo_items = TodoItem.objects.filter(completed_date__isnull=True)
    order = request.GET.get('order', 'priority')
    if order == 'alphabetical':
        todo_items = todo_items.order_by('text')
    elif order == 'priority':
        todo_items = todo_items.order_by('-priority__order')
    elif order == 'random':
        todo_items = list(todo_items.all())
        random.shuffle(todo_items)
    else:
        todo_items = todo_items.all()

    completed_items = TodoItem.objects.filter(completed_date__isnull=False)

    # todo_items = TodoItem.objects.all()
    # todo_items = todo_items.filter(text='wash the dog')
    # todo_items = todo_items.order_by('text')
    # print(todo_items)

    todo_priorities = TodoItemPriority.objects.order_by('-order')
    context = {
        'title': 'Todo List ' + emoji,
        'error': '',
        'todo_items': todo_items,
        'completed_items': completed_items,
        'todo_priorities': todo_priorities,
    }
    return render(request, 'todoapp/index.html', context)

def savetodo(request):
    print(request.POST)

    # get data out of dictionary
    todo_text = request.POST['todo_text']
    todo_priority_id = request.POST['todo_priority_id']

    # create an instance of our model
    # TodoItemPriority.objects.get(name='high')
    # todo_priority = TodoItemPriority.objects.get(id=todo_priority_id)
    # todo_item = TodoItem(text=todo_text, priority=todo_priority)

    todo_item = TodoItem(text=todo_text, priority_id=todo_priority_id)

    # save the instance
    todo_item.save()

    # redirect back to the index view
    return HttpResponseRedirect(reverse('todoapp:index'))


def completetodo(request):
    todo_item_id = request.POST['todo_item_id']
    todo_item = TodoItem.objects.get(id=todo_item_id)
    if todo_item.completed_date is None:
        todo_item.completed_date = timezone.now()
    else:
        todo_item.completed_date = None
    todo_item.save()
    return HttpResponseRedirect(reverse('todoapp:index'))


def deletetodo(request, todo_item_id):
    todo_item = TodoItem.objects.get(id=todo_item_id)
    todo_item.delete()
    return HttpResponseRedirect(reverse('todoapp:index'))

Code/Teddy/Django/todoproj/todoapp/templates/todoapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Todo List</title>

    <!-- Materialize.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    <style type="text/css">
      .super_high {
        color:gold;
        font-weight:bold;
      }
      .high {
        color:red;
      }
      .medium {
        color:orange;
      }
      .low {
        color:blue;
      }
      main {
        max-width:600px;
        margin: 0 auto;
        padding:10px;
      }
      .sorting_bts {
        display:flex;
        flex-direction:row;
        justify-content:space-evenly;
      }
      @media (max-width:600px) {
        .sorting_bts {
          flex-direction:column;
        }
        .sorting_bts a {
          margin:5px;
        }
      }
      .collection-item {
        display:flex;
        flex-direction:row;
        justify-content:space-between;
        align-items:center;
        font-size:20px;
      }
      .collection-item .btns {
        display:flex;
        flex-direction:row;
      }
      .collection-item .btns > * {
        margin-left:10px;
      }
      .collection-item:nth-child(even) {
        background-color:whitesmoke;
      }
      body {
        background-color: #0F4C81;
      }
      main {
        background-color:white;
        min-height:100vh;
      }
      .completed {
        color:grey;
        text-decoration:line-through;
      }
    </style>
  </head>
  <body>
    <main>

      {% if error %}
      <div style="color:red">{{error}}</div>
      {% endif %}
      <h1>{{ title }}</h1>


      <div class="row">
        <form class="col s12" action="{% url 'todoapp:savetodo' %}" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="input-field col s12 m5">
              <input id="todo_text" type="text" name="todo_text" class="validate" required/>
              <label for="todo_text">Todo Text</label>
            </div>
            <div class="input-field col s12 m5">
              <!-- priority select -->
              <select id="todo_priority_id" name="todo_priority_id" required class="validate">
                <option value="" selected disabled>Select a priority</option>
                {% for priority in todo_priorities %}
                <option value="{{ priority.id }}">{{ priority.name | title }}</option>
                {% endfor %}
              </select>
              <label for="todo_priority_id">Priority</label>
            </div>
            <div class="input-field col s12 m2">
              <button type="submit" class="btn">submit</button>
            </div>
          </div>
        </form>
      </div>

      <div class="sorting_bts">
        <a href="?order=default" class="btn blue">default</a>
        <a href="?order=alphabetical" class="btn blue">alphabetical</a>
        <a href="?order=priority" class="btn blue">priority</a>
        <a href="?order=random" class="btn blue">random</a>
      </div>

      <ul class="collection">
        {% for todo_item in todo_items %}
        <li class="collection-item {{ todo_item.priority.get_class_name }}">
          <span>{{todo_item.text}} ({{todo_item.priority.name}})</span>
          <div class="btns">
            <a href="{% url 'todoapp:deletetodo' todo_item.id %}" class="btn orange"><i class="material-icons">clear</i></a>
            <form action="{% url 'todoapp:completetodo' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="todo_item_id" value="{{todo_item.id}}"/>
              <button type="submit" class="btn blue"><i class="material-icons">check_box_outline_blank</i></button>
            </form>
          </div>
        </li>
        {% endfor %}

        {% for todo_item in completed_items %}
        <li class="collection-item completed">
          <span>{{todo_item.text}} ({{todo_item.priority.name}})</span>
          <div class="btns">
            <a href="{% url 'todoapp:deletetodo' todo_item.id %}" class="btn orange"><i class="material-icons">clear</i></a>
            <form action="{% url 'todoapp:completetodo' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="todo_item_id" value="{{todo_item.id}}"/>
              <button type="submit" class="btn blue"><i class="material-icons">check_box</i></button>
            </form>
          </div>
        </li>
        {% endfor %}
      </ul>

    </main>
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, {});
      });
    </script>
  </body>
</html>