Code/Curt/django/djangolabs/djangolabs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab2app/', include('lab2app.urls')),
    path('lab3app/', include('lab3app.urls')),
    path('lab4app/', include('lab4app.urls')),
]

Code/Curt/django/djangolabs/lab2app/urls.py
from django.urls import path
from . import views

app_name = 'lab2app'
urlpatterns = [
    path('', views.index, name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('contacts/<int:contact_item_id>/', views.contact_id, name='contact_id'),
    path('contacts/new/', views.new_contact, name='new_contact'),
    path('contacts/<int:contact_item_id>/edit/', views.edit_contact, name='edit_contact'),
    path('contacts/update/<int:contact_item_id>/', views.update_contact, name='update_contact'),
    path('contacts/new/', views.new_contact, name='new_contact'),
    path('contacts/delete/<int:contact_item_id>/', views.delete_contact, name='delete_contact'),
]

Code/Curt/django/djangolabs/lab2app/models.py
from django.db import models

class Contact(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    birthday = models.DateField()
    phone_number = models.CharField(max_length=200)
    is_cell = models.BooleanField()

    def __str__(self):
        cellstat = self.cellstat()
        return self.last_name + ', ' + self.first_name + ' | ' + str(self.birthday) + ' | ' + self.phone_number + ' | Cell Phone: ' + str(cellstat)

    def cellstat(self):
        if self.is_cell:
            cellstat = "Yes"
        else:
            cellstat = "No"
        return cellstat

    def formatted_birthday(self):
        return self.birthday.strftime('%Y/%m/%d')

Code/Curt/django/djangolabs/lab2app/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Contact
import datetime
#HttpResponse(reverse("lab2app:index"))

def index(request):
    return HttpResponse("This is the index page.")

def contacts(request):
    contact_list = Contact.objects.all()
    context = {
        "contact_list": contact_list
    }
    return render(request, "lab2app/contacts.html", context)

def contact_id(request, contact_item_id):
    contact_details = Contact.objects.get(id=contact_item_id)
    context = {
        "contact_details": contact_details
    }
    return render(request, "lab2app/contact_id.html", context)

def new_contact(request):
    return HttpResponse("This is the new contacts page")

def edit_contact(request, contact_item_id):
    contact_details = Contact.objects.get(id=contact_item_id)
    context = {
        "contact_details": contact_details
    }
    return render(request, "lab2app/edit_contact.html", context)

def new_contact(request):
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    birthday = request.POST['birthday']
    phone_number = request.POST['phone_number']
    if 'is_cell' in request.POST:
        is_cell = True
        cellstat = "Yes"
    else:
        is_cell = False
        cellstat = "No"

    birthday = birthday.replace('/','-')
    print(request.POST)
    new_contact = Contact(first_name=first_name, last_name=last_name, birthday=birthday, phone_number=phone_number, is_cell=is_cell)

    # save the instance
    new_contact.save()

    # redirect back to the index view
    return HttpResponseRedirect(reverse('lab2app:contacts'))

def update_contact(request, contact_item_id):
    contact_details = Contact.objects.get(id=contact_item_id)
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    birthday = request.POST['birthday']
    phone_number = request.POST['phone_number']
    if 'is_cell' in request.POST:
        is_cell = True
        cellstat = "Yes"
    else:
        is_cell = False
        cellstat = "No"

    birthday = datetime.datetime.strptime(birthday, '%Y/%m/%d').date()
    # birthday = date(birthday).isoformat()

    contact_details.first_name = first_name
    contact_details.last_name = last_name
    contact_details.birthday = birthday
    contact_details.phone_number = phone_number
    contact_details.is_cell = is_cell
    contact_details.cellstat = cellstat

    # save the instance
    contact_details.save()

    # redirect back to the index view
    return HttpResponseRedirect(reverse('lab2app:contacts'))

def delete_contact(request, contact_item_id):
    Contact.objects.filter(id=contact_item_id).delete()
    return HttpResponseRedirect(reverse('lab2app:contacts'))

Code/Curt/django/djangolabs/lab2app/templates/lab2app/contact_id.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>

<ul class="collection with-header striped">
  <li class="collection-header"><h4>{{contact_details.first_name}} {{contact_details.last_name}}</h4></li>
  <h5><li class="collection-item">Birthdate: {{contact_details.birthday}}</li>
  <li class="collection-item">Phone Number: {{contact_details.phone_number}}</li>
  <li class="collection-item">Cellphone? {{contact_details.cellstat}}</li></h5>
</ul>
  <a class="waves-effect waves-light btn" style="margin-left:20px;" href="{% url 'lab2app:contacts' %}">Home</a>
  </body>
</html>

Code/Curt/django/djangolabs/lab2app/templates/lab2app/contacts.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Materialize.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="/static/lab2app/stylesheet.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>
      <h1 class=center-align>My Contacts</h1>
      <table class="responsive-table striped center-align teal">
        <thead>
          <th>Name (First, Last)</th>
          <th>Birthday</th>
          <th>Phone Number</th>
          <th>Cell Phone?</th>
        </thead>

        <tbody>
          {% for contact_item in contact_list %}
          <tr>
            <td>{{contact_item.first_name}} {{contact_item.last_name}}</td>
            <td>{{contact_item.birthday}}</td>
            <td>{{contact_item.phone_number}}</td>
            <td>{{contact_item.cellstat}}</td>
            <td><div class="row">
              <a class="waves-effect waves-light btn" href="{% url 'lab2app:contact_id' contact_item.id %}">View</a>
              <a class="waves-effect waves-light btn" href="{% url 'lab2app:edit_contact' contact_item.id %}">Edit</a>
              <a class="waves-effect waves-light btn" href="{% url 'lab2app:delete_contact' contact_item.id %}">Delete</a>
            </div></td>
          </tr>
          {% endfor %}
          <tr>
            <form class="" action="{% url 'lab2app:new_contact' %}" method="post">
            {% csrf_token %}
              <td><div class="row">
                <input type="text" name="first_name" placeholder=" First Name" class="white s5 col" style="margin-right:10px!important;"/>
                <input type="text" name="last_name" placeholder=" Last Name" class="white s5 col"/>
              </div></td>
              <td><div class="row">
                <input type="text" name="birthday" placeholder=" Birthday" class="datepicker" style="background-color:white;">
              </div></td>
              <td><div class="row">
                <input type="text" name="phone_number" placeholder=" Phone Number" class="white"/>
              </div></td>
              <td><div class="row">
                <label>
                  <input type="checkbox" name="is_cell"/>
                  <span style="color:black">Cell Phone</span>
                </label>
                </div></td>
              <td><div class="row">
                  <button type="submit" class="waves-effect waves-light btn" style="margin-left:20px;" href="{% url 'lab2app:new_contact' %}">Save</button>
              </div></td>
            </form>

          </tr>
        </tbody>
      </table>
      <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('.datepicker');
          var instances = M.Datepicker.init(elems, {
            format:"yyyy/mm/dd",
            defaultDate: new Date( "{{contact_details.formatted_birthday}}"),
            setDefaultDate: true
          });
        });
      </script>
  </body>
</html>

Code/Curt/django/djangolabs/lab2app/templates/lab2app/edit_contact.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <h1>Edit Contact:</h1>
    <form class="" action="{% url 'lab2app:update_contact' contact_details.id %}" method="post">
    {% csrf_token %}
      <ul class="collection striped">
        <li class="collection-item"><div class="row"><h5>
          <span>Name:</span><br>
          <input type="text" name="first_name" value="{{contact_details.first_name}}" class="s5 col" style="margin-right:10px; font-size:20px">
          <input type="text" name="last_name" value="{{contact_details.last_name}}" class="s5 col" style="font-size:20px">
        </h5></div></li>
        <li class="collection-item"><div class="row"><h5>
          <span>Birthdate:</span><br>
          <input type="text" name="birthday"  class="datepicker s5 col" style="font-size:20px">
        </h5></div></li>
        <li class="collection-item"><div class="row"><h5>
          <span>Phone Number:</span><br>
          <input type="text" name="phone_number" value="{{contact_details.phone_number}}" class="s5 col" style="font-size:20px">
        </h5></div></li>
        <li class="collection-item"><div class="row"><h5>

          <label>
            <input type="checkbox" {% if contact_details.is_cell %}checked{% endif %} name="is_cell"/>
            <span style="color:black; font-size:1.64rem">Cell Phone</span>
          </label>

        </h5></div></li>
      </ul>
      <button type="submit" class="waves-effect waves-light btn" style="margin-left:20px;" href="{% url 'lab2app:update_contact' contact_details.id %}">Save</button>
      <a class="waves-effect waves-light btn" style="margin-left:20px;" href="{% url 'lab2app:contacts' %}">Cancel</a>
    </form>
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(elems, {
          format:"yyyy/mm/dd",
          defaultDate: new Date( "{{contact_details.formatted_birthday}}"),
          setDefaultDate: true
        });
      });
    </script>
  </body>
</html>

Code/Curt/django/djangolabs/lab2app/templates/lab2app/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="/static/lab2app/stylesheet.css">

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>
  </body>
</html>